# Generated by Django 4.2.2 on 2023-07-02 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudUserFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField()),
                ('file_data', models.TextField()),
                ('file_type', models.CharField(max_length=128)),
                ('file_url', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userFiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
