# Generated by Django 4.2.2 on 2023-07-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_clouduserfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='clouduserfiles',
            name='file_comment',
            field=models.TextField(blank=True),
        ),
    ]
